import { NextApiRequest, NextApiResponse } from 'next';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json({
    day: '토요일',
    title: '6일차 적군 토벌 (승차점수 4점)',
    rewards: [
      { item: 'UR 교역 화물차 1회 출발', reward: 300000 },
      { item: 'UR 은밀한 임무 1개 수행', reward: 225000 },
      { item: '건설 가속 1분 사용', reward: 150 },
      { item: '테크 가속 1분 사용', reward: 150 },
      { item: '훈련 가속 1분 사용', reward: 150 },
      { item: '치료 가속 1분 사용', reward: 150 },
      { item: '1레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 30 },
      { item: '2레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 45 },
      { item: '3레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 60 },
      { item: '4레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 75 },
      { item: '5레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 90 },
      { item: '6레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 105 },
      { item: '7레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 120 },
      { item: '8레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 135 },
      { item: '9레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 150 },
      { item: '10레벨 유닛 1개 처치 (특정 매칭 연맹)', reward: 165 },
      { item: '1레벨 유닛 1개 처치', reward: 6 },
      { item: '2레벨 유닛 1개 처치', reward: 9 },
      { item: '3레벨 유닛 1개 처치', reward: 12 },
      { item: '4레벨 유닛 1개 처치', reward: 15 },
      { item: '5레벨 유닛 1개 처치', reward: 18 },
      { item: '6레벨 유닛 1개 처치', reward: 21 },
      { item: '7레벨 유닛 1개 처치', reward: 24 },
      { item: '8레벨 유닛 1개 처치', reward: 27 },
      { item: '9레벨 유닛 1개 처치', reward: 30 },
      { item: '10레벨 유닛 1개 처치', reward: 33 },
      { item: '1레벨 유닛 1개 전사', reward: 5 },
      { item: '2레벨 유닛 1개 전사', reward: 7.5 },
      { item: '3레벨 유닛 1개 전사', reward: 10 },
      { item: '4레벨 유닛 1개 전사', reward: 12.5 },
      { item: '5레벨 유닛 1개 전사', reward: 15 },
      { item: '6레벨 유닛 1개 전사', reward: 17.5 },
      { item: '7레벨 유닛 1개 전사', reward: 20 },
      { item: '8레벨 유닛 1개 전사', reward: 22.5 },
      { item: '9레벨 유닛 1개 전사', reward: 25 },
      { item: '10레벨 유닛 1개 전사', reward: 27.5 },
      { item: '다이아 포함 패키지 구매 (1다이아)', reward: 30 },
    ],
    items: [
      'UR 교역 화물차 출발',
      '주황 은밀한 임무 수행',
      '건설 가속 사용',
      '테크 가속 사용',
      '훈련 가속 사용',
      '치료 가속 사용',
      '유닛 처치 (특정 매칭 연맹)',
      '유닛 처치',
      '유닛 전사',
      '다이아 포함 패키지 구매',
    ],
  });
}
